### ISSUE TITLE
`set_target_temperature`, `turn_on` and `turn_off` functions are not working.

### ISSUE THREAD

**Issue by pxpress** [frenck/python-fumis#36]
I have tried to use your project to monitor and control my fumis burner. I successfully installed the package and ran the example script.

I was able to connect to the WiRCU and get the current state of the burner. Unfortunately, I was not able to `set_target_temperature`, `turn_on` or `turn_off` the burner. Is there any available documentation about the API you are using to investigate why I am failing to control my burner.

**Comment by frenck** [comment]
Yep, this is an issue I haven't figured out yet.
My original plan was to bring this to Home Assistant, however, the failing of controlling the settings is the reason why I have not done that yet.

I've spend hours of debugging, but could not figure it out. If I take the exact request I send from this Library into a tool like Postman, it works.

That is currently where I'm stranded.

**Comment by pxpress** [comment]
Hmmm, that sounds pretty interesting. Have you consider about the spacing like indentations, tabs, and new line format? I will try to set up an testing environment with Postman and test a few things.

Thank you for your fast response!

**Comment by frenck** [comment]
Yes, I've even dumped the exact requests from python, pasted them raw into postman -> Work with postman, not with Python.
Additional weird thing, the Python requests do not fail on the server end, so they are accepted and have a proper response code.

**Comment by pxpress** [comment]
Is this the structure of the request for setting the temperature in PostMan?
```
POST /v1/status HTTP/1.1
Host: api.fumis.si
Accept: application/json
User-Agent: PythonFumis/0.1.0
appname: PythonFumis
username: <MAC>
password: <PIN>
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: <TOKEN>
Accept-Encoding: gzip, deflate
Referer: https://api.fumis.si/v1/status
Connection: keep-alive
cache-control: no-cache

{
    "unit": {
        "id": "<MAC>",
        "type": 0,
        "pin": "<PIN>"
    },
    "apiVersion": "1",
    "controller": {
        "temperatures": [
            {
                "set": 23,
                "id": 1
            }
        ],
        "type": 0
    }
}
```

Because I only receive the current status of the stove, but the change has no effect.

**Comment by maheus** [comment]
@frenck i think that i find the solution.
if you adding a slash to the url , the temp is set.
url: api.fumis.si/v1/status/

i 'm going to try add some functionnalities and adding plugin to homeassistant.

**Comment by frenck** [comment]
I have a full-blown (platinum grade) integration for HA ready for Fumis.
But ran into library issues. Even with the suggested added slashes, the returned response was 200, but the changes were not actually applied.

**Comment by maheus** [comment]
It is rallye curious my changes is applied
I will post my traces

**Comment by maheus** [comment]
```
        data = await fumis.set_target_temperature(19.0)
        "temperatures": [
            {
                "actual": 22,
                "actualType": 1,
                "id": 1,
                "name": null,
                "onMainScreen": true,
                "set": 19,
                "setType": 2,
                "weight": 0
            },
```

**Comment by maheus** [comment]
after check my ui on the stove , the temperature is set correctly.

**Comment by maheus** [comment]
do you can in http and take a trace with ngrep ( ngrep -d any host api.fumis.si , on linux ) @frenck

**Comment by maheus** [comment]
@frenck do you can commit your homeassistant integration for fumis on github, please.
i will test .

**Comment by frenck** [comment]
Not now, I can see if I can free up some time soon.

**Comment by jerbob92** [comment]
I'm also interested in this. How is the stability of your Fumis cloud connection?
Mine seems to disconnect a lot and then I can't control it from the Fumis app

**Comment by maheus** [comment]
@jerbob92 , no stabilities problem for me . it seems a little bit slow so i will wait between two and five minutes before the change is applied

**Comment by jerbob92** [comment]
@maheus Are you sure that's not related to it being unstable? Because changes taking 2-5 minutes doesn't really sound like a usable API integration to me. I did some digging into the API and a lot of times I'm getting connection resets.

**Comment by maheus** [comment]
@jerbob92 for me ,the changes on the api is  immediate but the changes on the stove is delayed 
I suppose that stove pull the changes regularly and if your connection is not fast the changes is slow

**Comment by jerbob92** [comment]
@maheus that's what I'm talking about, if the connection between the stove and the cloud API is unstable, it could be a reason the changes take so long to take effect. For me, the WiRCU seems to reboot a couple times every hour.

**Comment by maheus** [comment]
ok @jerbob92  it is strange, i don't think that mine has this problem
i 'm going to add a http  test to wircu http ihm for validate or not your hypothesis

**Comment by jerbob92** [comment]
I also tried to create a direct connection between Google Smart Home and Fumis, without home assistent. I got actually quite far, but it looks like the Google Home app doesn't support the device type "Heater" (https://developers.google.com/assistant/smarthome/guides/heater), so it wasn't really usable from the Home App, but you could use the voice commands, but for me Home App support is more important, I don't like talking to my devices :P

**Comment by maheus** [comment]
![Capture d’écran_2020-07-27_15-25-41](https://user-images.githubusercontent.com/2638802/88547047-7d1e7b00-d01d-11ea-84e3-b5eeb9eca4c6.png)
@jerbob92 test without problem, i think that your wircu module is faulty

**Comment by jerbob92** [comment]
Thanks for checking :) Already mailed Fumis en the stove manufacturer, sadly no reply yet.

**Comment by valdiks** [comment]
Can somebody to help how to send http json request to turn on/off?
Cannot figure out.
Trying to configure through Node Red.

**Comment by frenck** [comment]
@valdiks that has absolutely 0 to do with all this here. Hid your comment.

**Comment by maheus** [comment]
@frenck @jerbob92 @pxpress  ,
i created my homeassistant integration based on the python-fumis lib , After one month there is no problem with my integration and associated automations 
only one error due to the fumis api who was down while some hours.

@frenck 
I found an issue with your lib, in the json structure, the  list of temperatures is not ordered by id .
example:
```
        "temperatures": [
            {
                "actual": 17,
                "actualType": 10,
                "id": 7,
                "name": null,
                "onMainScreen": false,
                "set": 0,
                "setType": 0,
                "weight": 0
            },
           {
                "actual": 23.4,
                 "actualType": 1,
                  "id": 1,
                  "name": null,
                  "onMainScreen": true,
                  "set": 19,
                  "setType": 2,
                   "weight": 0
            },
        {
]
```

your lib (` temperature = temperatures[0] if temperatures else {}`) send 17 instead of 23.4.
I changed your code  by 
```
        if temperatures:
            temperature = [d for d in temperatures if d["id"] == STOVE_ID][0]
        else:
            temperature = {}
```
where STOVE_ID is 1 (but it can be manageable)

**Comment by pxpress** [comment]
> @frenck @jerbob92 @pxpress ,
> i created my homeassistant integration based on the python-fumis lib , After one month there is no problem with my integration and associated automations
> only one error due to the fumis api who was down while some hours.

@maheus Cool! I think I managed to find that the packages that my fumis device is receiving for setting the temperature and power on and off are slightly different from the one in this project. I will test the modification and share the results. I am also working on Home assistant module but at this time I am in the very beginning.

**Comment by frenck** [comment]
Nice! So for the state of things, if any of you wants to copy/fork/adopt the lib. Please do so.

I don't have access to a Fumis WiRCU anymore and I have some serious concerns with Fumis in general (for which I'll contact ATech directly).

**Comment by rmpirescosta** [comment]
I would like to know how the project is going, as I have a fumis and I would like to integrate it into the home assistant

**Comment by maheus** [comment]
Hi @rmpirescosta ,

do you have try this lib ?
I can you send my integration for your testing

**Comment by rmpirescosta** [comment]
yes i would like to try. will be able to send. I am not very experienced in this field but I will try to install and test it. Thank you very much in advance

**Comment by maheus** [comment]
ok @rmpirescosta , you can download tar in my repo https://github.com/maheus/fumis_integration (open an issue in this repo if you have a problem)
